# Generated by Django 6.0.7 on 2026-07-25 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reposts_count',
            new_name='reposts',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
