# Generated by Django 6.0.7 on 2026-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_reposts_count_post_reposts_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
